name             'dealhunter'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures dealhunter'
long_description 'Installs/Configures dealhunter'
version          '0.1.0'
